export class CoinReduceHalf {

     besttransactionfees: string;
    // tslint:disable-next-line:variable-name
     block_profit: string;
    // tslint:disable-next-line:variable-name
     block_size: string;
    // tslint:disable-next-line:variable-name
     blocks_count: string;
    // tslint:disable-next-line:variable-name
     computing_power: string;
    // tslint:disable-next-line:variable-name
     computing_power_income: string;
    // tslint:disable-next-line:variable-name
     current_block_reward_count: string;
     difficulty: string;
     feesunit: string;
     genesisblocktime: string;
    // tslint:disable-next-line:variable-name
     new_announcer: string;
    // tslint:disable-next-line:variable-name
     new_broadcast_hashaddr: string;
    // tslint:disable-next-line:variable-name
     new_broadcast_time: string;
    // tslint:disable-next-line:variable-name
     new_confirmed_txns24hcount: string;
    // tslint:disable-next-line:variable-name
     new_txns24hcount: string;
     nextdifficultydate: string;
     nextdifficultyestimated: string;
    // tslint:disable-next-line:variable-name
     reducehalf_block_count: string;
     txns24hcount: string;
     txnscount: string;
     txrate24h: string;
    // tslint:disable-next-line:variable-name
     unconfirmed_txns24hcount: string;
    // tslint:disable-next-line:variable-name
     volume_median: string;
}
